#!/bin/bash
# Manage a goals file
#
# Copyright (C) 2013 Mark Harrison
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

ACTION=$1

if [[ $ACTION == "usage" ]]; then
    echo "    goals"
    echo "      View/manage a goals file"
    echo "      No arguments: view the goals file"
    echo "      Arguments: add an entry to the goals file"
    exit
fi
shift

# You can configure a goals file with the TODO_GOALS_FILE variable, or it will
# default to goals.txt inside your todo directory
if [[ -z $TODO_GOALS_FILE ]]; then
    TODO_GOALS_FILE=goals.txt
fi

if [[ -n $2 ]]; then
    $TODO_FULL_SH addto $TODO_GOALS_FILE "$@"
else
    $TODO_FULL_SH listfile $TODO_GOALS_FILE
fi
