#!/bin/bash

action=$1
shift

function usage() {
  echo "  Navigate to URL:"
  echo "    open ITEM#"
  echo "      Searches for a URL in the todo line and launches a browser."
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echo "Error! Usage:"
    usage
fi

URL=$(sed "$1!d" "$TODO_FILE"|grep -E -o "([a-z]*)://[^ ]+|(go|cs|cl)/[^ ]+")
if [ "$URL" = "" ]; then
    LINE=$(sed "$1!d" "$TODO_FILE")
    if [ "$LINE" = "" ]; then
        echo "Error, no item #$1 found!"
    else
        echo "Error, no URL seen in item #$1!"
        echo "$LINE"
    fi
    exit 1
fi

if [[ $URL != *"://"* ]]; then
  URL="http://$URL"
fi

if $(which x-www-browser >/dev/null 2>&1); then
    exec x-www-browser "$URL"
elif $(which xdg-open >/dev/null 2>&1); then
    exec xdg-open "$URL"
elif [ -x "/usr/bin/open" ]; then
    exec "/usr/bin/open" "$URL"
else
    echo "Sorry I'm giving up, cannot find your browser :-("
fi
