#!/bin/sh

#gnome-settings-daemon &
#unity-settings-daemon &
cinnamon-settings-daemon &

#gnome-terminal &

if [ -x `which drive-sync` ]; then
  drive-sync &
fi

if [ -x `which xautolock` ]; then
  xautolock -time 5 -locker "i3lock -c 333333" &
fi

if [ -x `which compton` ]; then
  compton --backend glx --inactive-dim 0.75 &
fi

#gnome-power-manager &

#gnome-volume-manager &

# i3
# necessary to make chrome pick up the proxy settings stored in gconf.
export DESKTOP_SESSION=gnome

# Disable audible bell
# xset -b

# Background color
if [ -x `which xsetroot` ]; then
  xsetroot -solid "#333333"
fi

exec i3
