#!/bin/sh

unity-settings-daemon &

#gnome-terminal &

drive-sync &

xautolock -time 5 -locker "i3lock -c 333333" &

#unity-power-manager &

unity-volume-manager &

# i3
# necessary to make chrome pick up the proxy settings stored in gconf.
export DESKTOP_SESSION=gnome

# Disable audible bell
xset -b

export GTK_IM_MODULE=xim

# Background color
xsetroot -solid "#333333"

exec i3
